version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql


  app:
    image: chebliaymen/aymenchebli-5arctic4-g3-kaddem:latest
    ports:
      - "8089:8089"  # Map host port 8089 to container port 8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddemdb?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    restart: on-failure  # Restart policy for the container
    stdin_open: true  # Keep standard input open to run commands
    tty: true  # Simulate a terminal interface
    depends_on:
      - mysqldb  # Ensure the app starts after the db service

  app-front:
    image: chebliaymen/aymenchebli-5arctic4-g3-kaddem-front:latest
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - app

volumes:
  db:  # Define a volume for the database